### ISSUE TITLE
Tile blobs fail to load from bigger database 

### ISSUE THREAD

**Issue by alexbodn** [jvail/spl.js#25] opened 2024-03-19 20:49 UTC
Bonne soirée mon ami.

I have finally published my first npm package, 
an embedded web based explorer for wasm sqlite 
databases, native and spl.js alike. Most of my work was done with spl.js as RDBMS.

When map viewers are installed, feature and tile tables have a map button by their side in the schema tab of SQLiteXplorer.

"sqlitexplorer - npm" https://www.npmjs.com/package/sqlitexplorer

If you'd be so kind to try it, you may observe
that png tile layers load fine from StLouis.gpkg .
However, the tiles won't load from the much bigger DCTour.gpkg.

To understand the gpkg is ok, you may try to load DCTour.gpkg in plain sqlite. Tile data may be viewed even though the RDBMS has no gis. Didn't want to implement loading of vector blobs, to avoid extra dependency on wkx.js.

Please enjoy.

**Comment by jvail** [comment] 2024-03-20 07:52
Hi @alexbodn, there is indeed a bug! The issue is that the emscripten memory array is recreated if it has been grown. I think it is fixed now. Would you like to give it a try with the new build in `dist/`? If it works for you I release a new version.

**Comment by alexbodn** [comment] 2024-03-20 09:44
thank you very much my friend,
the bug appears to be fixed.

**Comment by alexbodn** [comment] 2024-03-20 11:32
> Hi @alexbodn, there is indeed a bug! The issue is that the emscripten memory array is recreated if it has been grown. I think it is fixed now. Would you like to give it a try with the new build in `dist/`? If it works for you I release a new version.

i remember a realloc function ;}

**Closed** 2024-03-20 11:31 UTC
